const config = {
    levels: {
        access:{
            color:[200,148,255],
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true,
        },
        warn:{
            color:"#ffff00",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        },
        debug:{
            color:"cyan",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        },
        system:{
            color:"blue",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        },
        database:{
            color:"cyanBright",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        },
        event:{
            color:"magenta",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        },
        info:{
            color:"green",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        },
        error:{
            color:"red",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        },
        fatal:{
            color:"redBright",
            writeToFile:true,
            sendToServer:true,
            sendToConsole:true
        }
    }
}

export default config;